use clap::{Arg, SubCommand, AppSettings, ArgGroup};

pub const CASINGS: [&'static str; 5] = 
    ["camel", "pascal", "lower underscore", "upper underscore", "hyphen"];
pub const CONFIG_CASINGS: [&'static str; 5] =
    ["config camel", "config pascal", "config lower underscore",
    "config upper underscore", "config hyphen"];
/// codic matches定義をゲットする
pub fn get_matches() -> clap::ArgMatches<'static> {

    clap::App::new("codic")
        .version("1.0")
        .author("asobi <asobininn2000@gmail.com>")
        .about("CodicAPIを用いて日本語を英語に翻訳する")
        .setting(AppSettings::ArgRequiredElseHelp)
        .arg(Arg::with_name("text")
            .help("翻訳したい日本語")
        )
        .arg(Arg::with_name(CASINGS[0])
            .help("camelCase")
            .short("c")
            .long("aA")
        )
        .arg(Arg::with_name(CASINGS[1])
            .help("PascalCase")
            .short("p")
            .long("AA")
        )
        .arg(Arg::with_name(CASINGS[2])
            .help("lower_case")
            .short("l")
            .long("a_a")
        )
        .arg(Arg::with_name(CASINGS[3])
            .help("UPPER_CASE")
            .short("u")
            .long("A_A")
        )
        .arg(Arg::with_name(CASINGS[4])
            .help("hyphen-case")
            .short("h")
            .long("a-a")
        )
        .group(ArgGroup::with_name("casing")
            .args(&CASINGS)
        )
        // configファイルの設定
        .subcommand(SubCommand::with_name("config")
            .about("configファイルの設定")
            .setting(AppSettings::ArgRequiredElseHelp)
            .arg(Arg::with_name("make")
                .help("デフォルトのコンフィグファイルを作成する")
                .short("m")
                .long("make")
            )
            .arg(Arg::with_name("show")
                .help("コンフィグファイルを表示する")
                .short("s")
                .long("show")
            )
            .arg(Arg::with_name("remove")
                .help("コンフィグファイルを削除する")
                .short("r")
                .long("remove")
            )
            .subcommand(SubCommand::with_name("edit")
                .about("コンフィグファイルの編集をする")
                .setting(AppSettings::ArgRequiredElseHelp)
                .arg(Arg::with_name("config token")
                    .help("APIキーの編集")
                    .short("t")
                    .long("token")
                    .takes_value(true)
                )
                .arg(Arg::with_name("config camel")
                    .help("デフォルトのcasingをcamelケースにする")
                    .long("c_aA")
                )
                .arg(Arg::with_name("config pascal")
                    .help("デフォルトのcasingをpascalケースにする")
                    .long("c_AA")
                )
                .arg(Arg::with_name("config lower underscore")
                    .help("デフォルトのcasingをlower underscoreケースにする")
                    .long("c_a_a")
                )
                .arg(Arg::with_name("config upper underscore")
                    .help("デフォルトのcasingをupper underscoreケースにする")
                    .long("c_A_A")
                )
                .arg(Arg::with_name("config hyphen")
                    .help("デフォルトのcasingをhyphenケースにする")
                    .long("c_a-a")
                )
                .group(ArgGroup::with_name("config casing")
                    .args(&CONFIG_CASINGS)
                )
            )
        )
        .get_matches()
}

